### ISSUE TITLE
Please update to 1.21 | Обновите на версию 1.21

### ISSUE THREAD

**Issue by Suilte** [noslowdwn/VoidFall#1]
При запуске сервера выдает

```
[02:05:24 INFO]: [VoidFall] Enabling VoidFall v1.2*
[02:05:24 ERROR]: Error occurred while enabling VoidFall v1.2 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.plugin.Plugin.isEnabled()" because "wgEvents" is null
        at VoidFall-1.2 (1).jar/noslowdwn.voidfall.VoidFall.onEnable(VoidFall.java:59) ~[VoidFall-1.2 (1).jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.jar:1.21-2263-87cf9f1]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.jar:1.21-2263-87cf9f1]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:643) ~[purpur-1.21.jar:1.21-2263-87cf9f1]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:592) ~[purpur-1.21.jar:1.21-2263-87cf9f1]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:756) ~[purpur-1.21.jar:1.21-2263-87cf9f1]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:518) ~[purpur-1.21.jar:1.21-2263-87cf9f1]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:361) ~[purpur-1.21.jar:1.21-2263-87cf9f1]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1234) ~[purpur-1.21.jar:1.21-2263-87cf9f1]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2263-87cf9f1]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
[02:05:24 INFO]: [VoidFall] Disabling VoidFall v1.2
```

Я понимаю, что плагин не может работать на версии 1.21, но версия плагина 1.1 спокойно запускается, но с багом. Баг этот заключается в том, что команды прописанные в конфиге работают всего 1 раз, несмотря на прописанное кол-во секунд между повторениями. Плагин с версией 1.2 попросту отказывается запускаться на версии 1.21, поэтому прошу обновить его

**Comment by groundbreakingmc** [comment]
Забыл ответить - было исправлено (еще очень давно), хех 😅
